version: '3.8'

services:
  app:
    build: .
    container_name: bookstore-api-app
    ports:
      - "3000:3000"
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=bookstore
      - PGPASSWORD=123456
      - PGPORT=5432
    depends_on:
      - db
    networks:
      - bookstpre-api-network

  db:
    image: postgres
    restart: always
    container_name: bookstore-api-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bookstore
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bookstpre-api-network

networks:
  bookstpre-api-network:

volumes:
  postgres-data:
